/** this file is automatically generated, do not edit **/

export type DiscordActivity = { name: string; type: string; details?: string | null; state?: string | null; hover_text?: string | null; asset_url?: string | null; start_time?: number | null; end_time?: number | null };
