use std::{convert::Infallible, env, io::Write};

use activity::{DiscordActivity, NoCopy};
use async_stream::stream;
use axum::{
    async_trait,
    extract::{Path, State},
    response::{
        sse::{Event, KeepAlive},
        IntoResponse, Response, Sse,
    },
    routing::get,
};
use events::Dispatcher;
use futures::Stream;
use imstr::ImString;
use serenity::{
    model::prelude::{Presence, Ready},
    prelude::{Context, EventHandler, GatewayIntents},
    Client,
};
use tokio::sync::mpsc::UnboundedReceiver;
use tower_http::cors::CorsLayer;

pub mod activity;
pub mod events;

macro_rules! specta_buffer {
    {$($types:ty)|* ,$s:expr} => {
        {
            use crate::activity::{ActivityType, Assets, BaseActivity, SpotifyActivity};

            let mut buffer = String::from("/** this file is automatically generated, do not edit **/\n\n");
            $(buffer += &specta::ts::export::<$types>(&Default::default()).expect("failed"); buffer += ";\n";)*
            buffer += $s;
            buffer
        }
    };
}

#[derive(Clone)]
struct AppState {
    dispatcher: Dispatcher<u64, ImString>,
    server_id: u64,
}

#[tokio::main]
async fn main() {
    // output definition files ONLY during development mode
    #[cfg(debug_assertions)]
    {
        println!("generating ts exports");
        let definitions = specta_buffer! {
            ActivityType | Assets | BaseActivity | SpotifyActivity | DiscordActivity,
            ""
        };
        let path = std::path::Path::new("./ts/activity.ts");

        // remove the file if it exists
        if path.exists() {
            std::fs::remove_file(path).expect("failed to remove file");
        }

        // write the file
        let mut file = std::fs::File::create(path).expect("failed to create file");
        file.write_all(definitions.as_bytes())
            .expect("failed to write file");
    }
    println!("Starting up...");

    let state = AppState {
        dispatcher: Dispatcher::new(),
        server_id: env::var("SERVER")
            .expect("Expected a server ID in the environment")
            .parse::<u64>()
            .expect("Expected a server ID in the environment"),
    };

    let s = state.clone();
    tokio::spawn(async move {
        let token = env::var("TOKEN").expect("Expected a token in the environment");

        let intents = GatewayIntents::GUILD_PRESENCES | GatewayIntents::GUILD_MEMBERS;

        let mut client = Client::builder(token, intents)
            .event_handler(s)
            .await
            .expect("Error creating client");

        if let Err(why) = client.start().await {
            println!("Client error: {:?}", why);
        }
    });

    let cors = CorsLayer::very_permissive();

    let app = axum::Router::new()
        .route("/", get(root))
        .route("/activity/:user_id", get(get_activity))
        .route("/live-activity/:user_id", get(live_activity))
        .layer(cors)
        .with_state(state);

    let addr = std::net::SocketAddr::from(([0, 0, 0, 0], 2223));

    println!("Listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn root() -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    Sse::new(stream! {
        loop {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            yield Ok(Event::default().data("Hello, world!"));
        }
    })
    .keep_alive(KeepAlive::new().interval(std::time::Duration::from_secs(10)))
}

const JSON_HEADERS: [(&str, &str); 2] = [
    ("Content-Type", "application/json"),
    ("Cache-Control", "no-cache"),
];

async fn get_activity(State(state): State<AppState>, Path(user_id): Path<u64>) -> Response {
    match state.dispatcher.last_event(user_id).await {
        Some(data) => {
            let data = data.into_bytes();
            (JSON_HEADERS, data).into_response()
        }
        None => (
            JSON_HEADERS,
            serde_json::to_string::<[String; 0]>(&[]).unwrap_or_default(),
        )
            .into_response(),
    }
}

fn create_stream(
    mut rx: UnboundedReceiver<ImString>,
    last_event: Option<ImString>,
) -> impl Stream<Item = Result<Event, Infallible>> {
    stream! {
        if let Some(data) = last_event {
            yield Ok(Event::default().data(data));
        }

        loop {
            match rx.recv().await {
                Some(data) => {
                    yield Ok(Event::default().data(data));
                }
                None => {
                    break;
                }
            }
        };
    }
}

async fn live_activity(State(state): State<AppState>, Path(user_id): Path<u64>) -> Response {
    let (rx, last_event) = state.dispatcher.subscribe(user_id).await;

    let stream = create_stream(rx, last_event);

    let sse =
        Sse::new(stream).keep_alive(KeepAlive::new().interval(std::time::Duration::from_secs(10)));

    return sse.into_response();
}

#[async_trait]
impl EventHandler for AppState {
    // As the intents set in this example, this event shall never be dispatched.
    // Try it by changing your status.
    async fn presence_update(&self, _ctx: Context, presence: Presence) {
        if presence.guild_id.unwrap_or_default().0 != self.server_id {
            return;
        }

        let user_id = presence.user.id.0;

        let activites = presence
            .activities
            .into_iter()
            .map(|a| a.into())
            .collect::<Vec<DiscordActivity>>();

        let data = activites.imstr();

        self.dispatcher.publish(user_id, data).await;
    }

    async fn ready(&self, _: Context, ready: Ready) {
        println!("{} is connected!", ready.user.name);
    }
}
